// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.13.0
// source: protocol/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Constants int32

const (
	Constants_Default Constants = 0 //0
	Constants_Magic   Constants = 49344
)

// Enum value maps for Constants.
var (
	Constants_name = map[int32]string{
		0:     "Default",
		49344: "Magic",
	}
	Constants_value = map[string]int32{
		"Default": 0,
		"Magic":   49344,
	}
)

func (x Constants) Enum() *Constants {
	p := new(Constants)
	*p = x
	return p
}

func (x Constants) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Constants) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_proto_enumTypes[0].Descriptor()
}

func (Constants) Type() protoreflect.EnumType {
	return &file_protocol_common_proto_enumTypes[0]
}

func (x Constants) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Constants.Descriptor instead.
func (Constants) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{0}
}

type SerializeFlag int32

const (
	SerializeFlag_PlainSerial SerializeFlag = 0 //普通文本
	SerializeFlag_PbSerial    SerializeFlag = 1 //pb
	SerializeFlag_JsonSerial  SerializeFlag = 2
	SerializeFlag_MaxSerial   SerializeFlag = 15
)

// Enum value maps for SerializeFlag.
var (
	SerializeFlag_name = map[int32]string{
		0:  "PlainSerial",
		1:  "PbSerial",
		2:  "JsonSerial",
		15: "MaxSerial",
	}
	SerializeFlag_value = map[string]int32{
		"PlainSerial": 0,
		"PbSerial":    1,
		"JsonSerial":  2,
		"MaxSerial":   15,
	}
)

func (x SerializeFlag) Enum() *SerializeFlag {
	p := new(SerializeFlag)
	*p = x
	return p
}

func (x SerializeFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SerializeFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_proto_enumTypes[1].Descriptor()
}

func (SerializeFlag) Type() protoreflect.EnumType {
	return &file_protocol_common_proto_enumTypes[1]
}

func (x SerializeFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SerializeFlag.Descriptor instead.
func (SerializeFlag) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{1}
}

type AuthCode int32

const (
	AuthCode_AuthSuccess AuthCode = 0
	AuthCode_AuthFailure AuthCode = 1
)

// Enum value maps for AuthCode.
var (
	AuthCode_name = map[int32]string{
		0: "AuthSuccess",
		1: "AuthFailure",
	}
	AuthCode_value = map[string]int32{
		"AuthSuccess": 0,
		"AuthFailure": 1,
	}
)

func (x AuthCode) Enum() *AuthCode {
	p := new(AuthCode)
	*p = x
	return p
}

func (x AuthCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_proto_enumTypes[2].Descriptor()
}

func (AuthCode) Type() protoreflect.EnumType {
	return &file_protocol_common_proto_enumTypes[2]
}

func (x AuthCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthCode.Descriptor instead.
func (AuthCode) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{2}
}

type ClientType int32

const (
	ClientType_ClientTypeUnknown ClientType = 0
	ClientType_ClientTypeIos     ClientType = 1
	ClientType_ClientTypeAndroid ClientType = 2
	ClientType_ClientTypeH5      ClientType = 3
)

// Enum value maps for ClientType.
var (
	ClientType_name = map[int32]string{
		0: "ClientTypeUnknown",
		1: "ClientTypeIos",
		2: "ClientTypeAndroid",
		3: "ClientTypeH5",
	}
	ClientType_value = map[string]int32{
		"ClientTypeUnknown": 0,
		"ClientTypeIos":     1,
		"ClientTypeAndroid": 2,
		"ClientTypeH5":      3,
	}
)

func (x ClientType) Enum() *ClientType {
	p := new(ClientType)
	*p = x
	return p
}

func (x ClientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_proto_enumTypes[3].Descriptor()
}

func (ClientType) Type() protoreflect.EnumType {
	return &file_protocol_common_proto_enumTypes[3]
}

func (x ClientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientType.Descriptor instead.
func (ClientType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{3}
}

type MsgType int32

const (
	MsgType_MsgTypeMin MsgType = 0 //0
	//client
	MsgType_MsgTypeAckClient MsgType = 256
	MsgType_MsgTypeKickOut   MsgType = 258
	//server msg
	//-----heartbeat----
	MsgType_MsgTypeHeartbeatUp   MsgType = 512
	MsgType_MsgTypeHeartbeatDown MsgType = 513
	//-----auth----
	MsgType_MsgTypeAuthUp         MsgType = 514
	MsgType_MsgTypeAuthDown       MsgType = 515
	MsgType_MsgTypeAuthVerifyUp   MsgType = 516
	MsgType_MsgTypeAuthVerifyDown MsgType = 517
	//client ack to server
	MsgType_MsgTypeAckServer MsgType = 765
	MsgType_MsgTypeServerMax MsgType = 767 //server msg end
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:   "MsgTypeMin",
		256: "MsgTypeAckClient",
		258: "MsgTypeKickOut",
		512: "MsgTypeHeartbeatUp",
		513: "MsgTypeHeartbeatDown",
		514: "MsgTypeAuthUp",
		515: "MsgTypeAuthDown",
		516: "MsgTypeAuthVerifyUp",
		517: "MsgTypeAuthVerifyDown",
		765: "MsgTypeAckServer",
		767: "MsgTypeServerMax",
	}
	MsgType_value = map[string]int32{
		"MsgTypeMin":            0,
		"MsgTypeAckClient":      256,
		"MsgTypeKickOut":        258,
		"MsgTypeHeartbeatUp":    512,
		"MsgTypeHeartbeatDown":  513,
		"MsgTypeAuthUp":         514,
		"MsgTypeAuthDown":       515,
		"MsgTypeAuthVerifyUp":   516,
		"MsgTypeAuthVerifyDown": 517,
		"MsgTypeAckServer":      765,
		"MsgTypeServerMax":      767,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_common_proto_enumTypes[4].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_protocol_common_proto_enumTypes[4]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{4}
}

type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType   uint32    `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	MsgId     uint64    `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	UserInfo  *UserInfo `protobuf:"bytes,3,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	Version   uint32    `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`     // 0， 升级版本递增1
	Timestamp uint64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` //unix时间戳，Java的话要 Instant.now().toMill()
	Ack       bool      `protobuf:"varint,8,opt,name=ack,proto3" json:"ack,omitempty"`             //是否进行应答，确认消息收到
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetMsgType() uint32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *Header) GetMsgId() uint64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Header) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Header) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{1}
}

func (x *Payload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        uint64     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"` //用户id
	Did        uint64     `protobuf:"varint,2,opt,name=did,proto3" json:"did,omitempty"` //设备id
	ClientType ClientType `protobuf:"varint,3,opt,name=clientType,proto3,enum=pb_generate.ClientType" json:"clientType,omitempty"`
	ClientVer  string     `protobuf:"bytes,4,opt,name=clientVer,proto3" json:"clientVer,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{2}
}

func (x *UserInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetDid() uint64 {
	if x != nil {
		return x.Did
	}
	return 0
}

func (x *UserInfo) GetClientType() ClientType {
	if x != nil {
		return x.ClientType
	}
	return ClientType_ClientTypeUnknown
}

func (x *UserInfo) GetClientVer() string {
	if x != nil {
		return x.ClientVer
	}
	return ""
}

//payload
//属性上报
type PropUpload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Props map[string]string `protobuf:"bytes,1,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PropUpload) Reset() {
	*x = PropUpload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropUpload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropUpload) ProtoMessage() {}

func (x *PropUpload) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropUpload.ProtoReflect.Descriptor instead.
func (*PropUpload) Descriptor() ([]byte, []int) {
	return file_protocol_common_proto_rawDescGZIP(), []int{3}
}

func (x *PropUpload) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

var File_protocol_common_proto protoreflect.FileDescriptor

var file_protocol_common_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x22, 0xb5, 0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12,
	0x31, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x63,
	0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x22, 0x23, 0x0a, 0x07,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x85, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x64,
	0x69, 0x64, 0x12, 0x37, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x22, 0x80, 0x01, 0x0a, 0x0a, 0x50, 0x72,
	0x6f, 0x70, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x38, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x2e, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x70, 0x72, 0x6f,
	0x70, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x25, 0x0a, 0x09,
	0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x05, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x10,
	0xc0, 0x81, 0x03, 0x2a, 0x4d, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65,
	0x46, 0x6c, 0x61, 0x67, 0x12, 0x0f, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x62, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4a, 0x73, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x61, 0x78, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x10, 0x0f, 0x2a, 0x2c, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0f,
	0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x01,
	0x2a, 0x5f, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15,
	0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x55, 0x6e, 0x6b, 0x6e,
	0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x6f, 0x73, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x41, 0x6e, 0x64, 0x72, 0x6f, 0x69, 0x64, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x48, 0x35, 0x10,
	0x03, 0x2a, 0x87, 0x02, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a,
	0x0a, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x4d, 0x69, 0x6e, 0x10, 0x00, 0x12, 0x15, 0x0a,
	0x10, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x41, 0x63, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x10, 0x80, 0x02, 0x12, 0x13, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x4b,
	0x69, 0x63, 0x6b, 0x4f, 0x75, 0x74, 0x10, 0x82, 0x02, 0x12, 0x17, 0x0a, 0x12, 0x4d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x55, 0x70, 0x10,
	0x80, 0x04, 0x12, 0x19, 0x0a, 0x14, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x10, 0x81, 0x04, 0x12, 0x12, 0x0a,
	0x0d, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x41, 0x75, 0x74, 0x68, 0x55, 0x70, 0x10, 0x82,
	0x04, 0x12, 0x14, 0x0a, 0x0f, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x44, 0x6f, 0x77, 0x6e, 0x10, 0x83, 0x04, 0x12, 0x18, 0x0a, 0x13, 0x4d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x41, 0x75, 0x74, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x70, 0x10, 0x84,
	0x04, 0x12, 0x1a, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x41, 0x75, 0x74, 0x68,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x6f, 0x77, 0x6e, 0x10, 0x85, 0x04, 0x12, 0x15, 0x0a,
	0x10, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x41, 0x63, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x10, 0xfd, 0x05, 0x12, 0x15, 0x0a, 0x10, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x78, 0x10, 0xff, 0x05, 0x42, 0x12, 0x5a, 0x10, 0x2e,
	0x2f, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_common_proto_rawDescOnce sync.Once
	file_protocol_common_proto_rawDescData = file_protocol_common_proto_rawDesc
)

func file_protocol_common_proto_rawDescGZIP() []byte {
	file_protocol_common_proto_rawDescOnce.Do(func() {
		file_protocol_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_common_proto_rawDescData)
	})
	return file_protocol_common_proto_rawDescData
}

var file_protocol_common_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_protocol_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protocol_common_proto_goTypes = []interface{}{
	(Constants)(0),     // 0: pb_generate.Constants
	(SerializeFlag)(0), // 1: pb_generate.SerializeFlag
	(AuthCode)(0),      // 2: pb_generate.AuthCode
	(ClientType)(0),    // 3: pb_generate.ClientType
	(MsgType)(0),       // 4: pb_generate.MsgType
	(*Header)(nil),     // 5: pb_generate.Header
	(*Payload)(nil),    // 6: pb_generate.Payload
	(*UserInfo)(nil),   // 7: pb_generate.UserInfo
	(*PropUpload)(nil), // 8: pb_generate.PropUpload
	nil,                // 9: pb_generate.PropUpload.PropsEntry
}
var file_protocol_common_proto_depIdxs = []int32{
	7, // 0: pb_generate.Header.userInfo:type_name -> pb_generate.UserInfo
	3, // 1: pb_generate.UserInfo.clientType:type_name -> pb_generate.ClientType
	9, // 2: pb_generate.PropUpload.props:type_name -> pb_generate.PropUpload.PropsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protocol_common_proto_init() }
func file_protocol_common_proto_init() {
	if File_protocol_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_common_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropUpload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_common_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_common_proto_goTypes,
		DependencyIndexes: file_protocol_common_proto_depIdxs,
		EnumInfos:         file_protocol_common_proto_enumTypes,
		MessageInfos:      file_protocol_common_proto_msgTypes,
	}.Build()
	File_protocol_common_proto = out.File
	file_protocol_common_proto_rawDesc = nil
	file_protocol_common_proto_goTypes = nil
	file_protocol_common_proto_depIdxs = nil
}
